# Generated by Django 6.0.6 on 2026-06-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='books.character'),
        ),
        migrations.AddField(
            model_name='scene',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='books.location'),
        ),
    ]
