# Generated by Django 6.0.6 on 2026-06-20 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название тома, части или главы', max_length=200)),
                ('number', models.PositiveIntegerField(help_text='Порядковый номер тома')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='books.book')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('book', 'number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='page',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='books.volume'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('book', 'volume', 'number')},
        ),
    ]
