# Generated by Django 6.0.6 on 2026-06-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_page_summary_volume_alter_page_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='location',
            name='avatar',
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('book', 'number')},
        ),
        migrations.AlterField(
            model_name='page',
            name='summary',
            field=models.TextField(blank=True, help_text='Краткий конспект страницы, сгенерированный LLM'),
        ),
        migrations.RemoveField(
            model_name='page',
            name='volume',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
